# -*- coding: utf-8 -*-
"""Enumerate_and_Zip.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uUDzmbfgryKYggldbNukBt1ynwPS2-TZ

# Enumerate and Zip in Python
"""

print('Welcome...!')

"""Iterable is an object which can be iterated, Iterator is an object which is iterating an iterable. Simple example for an iterable is list.

To be more techniqual, any python object related with iter() method is known as iterable.
"""

# Create a list of strings: flash
flash = ['jay garrick', 'barry allen', 'wally west', 'bart allen']

# Print each list item in flash using a for loop
for i in flash:
    print(i)

print('===================')
# Create an iterator for flash: superspeed
superspeed = iter(flash)

# Print each item from the iterator
print(next(superspeed))
print(next(superspeed))
print(next(superspeed))
print(next(superspeed))

"""### Enumerate

Enumerate is a function in python which takes list as an argument and returns the list values with their indexes as tuples.
"""

# Create a list of strings: mutants
mutants = ['charles xavier', 
           'bobby drake', 
            'kurt wagner', 
            'max eisenhardt', 
            'kitty pryde']

# Create a list of tuples: mutant_list
mutant_list = list(enumerate(mutants,0))

# Print the list of tuples
print(mutant_list)

# Unpack and print the tuple pairs
for index1, value1 in enumerate(mutants):
    print(index1, value1)

"""enumarete(list, index = 0), as shown enumerate function takes two argument, the second argument tells from which number the indexing has to be done.

lets try, strating our index from 1
"""

# Change the start index
for index2, value2 in enumerate(mutants,1):
    print(index2, value2)

"""### Zip

Zip function gets arbitery number of same sized lists, combine them and return as tuples.
"""

student = ['John', 'Bob', 'alis', 'drek']
degree = ['bachelor','Masters', 'bachelor', 'Masters']
field = ['Computing', 'Physics', 'Business','Computing']

# Create a list of tuples: student_data
student_data = list(zip(student, degree, field))

# Print the list of tuples
print(student_data)

# Create a zip object using the three lists: student_zip
student_zip = zip(student, degree, field)

# Print the zip object
print(student_zip)

# Unpack the zip object and print the tuple values
for value1, value2, value3 in student_zip:
    print(value1, value2, value3)

print('Happy Coding..!')

"""Happy Coding...!"""

